# Generated by Django 4.2.5 on 2023-11-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NombreHostal', models.CharField(max_length=20)),
                ('direccionHostal', models.CharField(max_length=20)),
                ('habitacionHostal', models.IntegerField()),
                ('tarifaHostal', models.FloatField()),
                ('phoneHostal', models.CharField(max_length=20)),
                ('numberHostal', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Hostal',
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='disponibilidad',
            field=models.CharField(max_length=20),
        ),
    ]
