# Generated by Django 4.2.5 on 2023-11-20 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0002_hotel_delete_hostal_alter_habitacion_disponibilidad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='NombreHostal',
            new_name='direccionHotel',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='habitacionHostal',
            new_name='habitacionHotel',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='direccionHostal',
            new_name='nombreHotel',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='numberHostal',
            new_name='numberHotel',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='phoneHostal',
            new_name='phoneHotel',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='tarifaHostal',
            new_name='tarifaHotel',
        ),
        migrations.RenameField(
            model_name='pasajero',
            old_name='apeliidoClint',
            new_name='apellidoClient',
        ),
    ]
