# Generated by Django 4.2.6 on 2023-12-03 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0004_alter_habitacion_cocina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='idHotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelApp.hotel'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pasajero',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='PasajeroHabitacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelApp.habitacion')),
                ('hotel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelApp.hotel')),
                ('pasajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelApp.pasajero')),
            ],
        ),
        migrations.AddField(
            model_name='pasajero',
            name='pedir',
            field=models.ManyToManyField(blank=True, through='hotelApp.PasajeroHabitacion', to='hotelApp.habitacion'),
        ),
    ]
