# Generated by Django 4.2.6 on 2023-12-05 16:07

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hotelApp', '0007_alter_pasajero_llegadaclient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='phoneHotel',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=15, region='CL', verbose_name='Numero de telefono del hotel'),
        ),
    ]
